#!/usr/bin/env python

# ros messages
import rospy
from std_msgs.msg import String

# board control
from rrb3 import *
rr = RRB3(9, 6)

# Message handler
def CommandCallback(commandMessage):
  command = commandMessage.data
  if command == 'forwards':
    rr.forward()
  elif command == 'backwards':
    rr.reverse()
  elif command == 'left':
    rr.left()
  elif command == 'right':
    rr.right()
  else:
    rr.stop()

# connection to ros
rospy.init_node('driver')
rospy.Subscriber('command', String, CommandCallback)
rospy.spin()

# stop motors and clean up the GPIO
rr.stop()
rr.cleanup()
